add inits fix install server for permission

diff --git a/inits/mongo/mongodb b/inits/mongo/mongodb
--- a/inits/mongo/mongodb
+++ b/inits/mongo/mongodb
@@ -47,8 +47,8 @@
 ### END INIT INFO
 
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
-DAEMON=/usr/sbin/mongod
-DATA=/data/db
+DAEMON=/usr/sbin/mongod 
+DATA=/data/db/
 NAME=mongodb
 DESC=database
 
@@ -63,18 +63,20 @@ fi
 
 . /lib/lsb/init-functions
 
+LOGDIR=/var/log/mongodb
 PIDFILE=/var/run/$NAME.pid
 DIETIME=10                   # Time to wait for the server to die, in seconds
                             # If this value is set too low you might not
                             # let some servers to die gracefully and
                             # 'restart' will not work
 
-DAEMON_OPTS="-f /etc/$NAME.conf"
+LOGFILE=$LOGDIR/$NAME.log  # Server logfile
+DAEMON_OPTS="--config /etc/$NAME.conf "
 
 
 # Include mongodb defaults if available
 if [ -f /etc/default/$NAME ] ; then
-    . /etc/default/$NAME
+	. /etc/default/$NAME
 fi
 
 DAEMONUSER=root
@@ -130,7 +132,7 @@ start_server() {
                         --exec $DAEMON -- $DAEMON_OPTS
             errcode=$?
         fi
-    return $errcode
+	return $errcode
 }
 
 stop_server() {
@@ -147,7 +149,7 @@ stop_server() {
             errcode=$?
         fi
 
-    return $errcode
+	return $errcode
 }
 
 reload_server() {
@@ -160,27 +162,27 @@ reload_server() {
 
 force_stop() {
 # Force the process to die killing it manually
-    [ ! -e "$PIDFILE" ] && return
-    if running ; then
-        kill -15 $pid
-    # Is it really dead?
-        sleep "$DIETIME"s
-        if running ; then
-            kill -9 $pid
-            sleep "$DIETIME"s
-            if running ; then
-                echo "Cannot kill $NAME (pid=$pid)!"
-                exit 1
-            fi
-        fi
-    fi
-    rm -f $PIDFILE
+	[ ! -e "$PIDFILE" ] && return
+	if running ; then
+		kill -15 $pid
+	# Is it really dead?
+		sleep "$DIETIME"s
+		if running ; then
+			kill -9 $pid
+			sleep "$DIETIME"s
+			if running ; then
+				echo "Cannot kill $NAME (pid=$pid)!"
+				exit 1
+			fi
+		fi
+	fi
+	rm -f $PIDFILE
 }
 
 
 case "$1" in
   start)
-    log_daemon_msg "Starting $DESC $NAME"
+	log_daemon_msg "Starting $DESC $NAME"
         # Check if it's running first
         if running ;  then
             log_progress_msg "apparently already running"
@@ -203,12 +205,12 @@ case "$1" in
             # Either we could not start it
             log_end_msg 1
         fi
-    ;;
+	;;
   stop)
         log_daemon_msg "Stopping $DESC" "$NAME"
         if running ; then
             # Only stop the server if we see it running
-            errcode=0
+			errcode=0
             stop_server || errcode=$?
             log_end_msg $errcode
         else
@@ -224,14 +226,14 @@ case "$1" in
         if running; then
             # If it's still running try to kill it more forcefully
             log_daemon_msg "Stopping (force) $DESC" "$NAME"
-            errcode=0
+			errcode=0
             force_stop || errcode=$?
             log_end_msg $errcode
         fi
-    ;;
+	;;
   restart|force-reload)
         log_daemon_msg "Restarting $DESC" "$NAME"
-        errcode=0
+		errcode=0
         stop_server || errcode=$?
         # Wait some sensible amount, some server need this
         [ -n "$DIETIME" ] && sleep $DIETIME
@@ -239,7 +241,7 @@ case "$1" in
         [ -n "$STARTTIME" ] && sleep $STARTTIME
         running || errcode=$?
         log_end_msg $errcode
-    ;;
+	;;
   status)
 
         log_daemon_msg "Checking status of $DESC" "$NAME"
@@ -283,10 +285,10 @@ case "$1" in
                                                                                     #;;
 
   *)
-    N=/etc/init.d/$NAME
-    echo "Usage: $N {start|stop|force-stop|restart|force-reload|status}" >&2
-    exit 1
-    ;;
+	N=/etc/init.d/$NAME
+	echo "Usage: $N {start|stop|force-stop|restart|force-reload|status}" >&2
+	exit 1
+	;;
 esac
 
 exit 0
